import org.apache.dubbo.config.spring.beans.factory.config.DubboConfigDefaultPropertyValueBeanPostProcessor;
public class FunctionUse1159 {
public void funcUse() {
DubboConfigDefaultPropertyValueBeanPostProcessor dubboconfigdefaultpropertyvaluebeanpostprocessor = new DubboConfigDefaultPropertyValueBeanPostProcessor();
dubboconfigdefaultpropertyvaluebeanpostprocessor.postProcessMergedBeanDefinition(null,null,null);
}
}