import istio.v1.auth.IstioCertificateServiceGrpc.IstioCertificateServiceBaseDescriptorSupplier;
public class FunctionUse283 {
public void funcUse() {
IstioCertificateServiceBaseDescriptorSupplier istiocertificateservicebasedescriptorsupplier = new IstioCertificateServiceBaseDescriptorSupplier();
istiocertificateservicebasedescriptorsupplier.getFileDescriptor();
}
}